Jalal Habeeb - Javascript-week3-Homework-class42
HackYourHomework/Homework-class42 pull request #11
Opened 2023-01-11 11:49 UTC by JalalHabeeb

2023-01-14 02:59 UTC, abbathaw requested changes
Great job on this homework. Your answers show that you are quite experienced with Javascript already. 

My only two comments are the following:
- Make sure the tests all pass (I left some comments on how to make them pass)
- Try and approach question 5 again and make it a really pure function.

Let me know you need any help.

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex1-giveCompliment.js
> +  return `You are ${compliments[randomCompliment]}, ${name}`;
Great work on this exercise. You are missing a `!` in the end of the line to make the test pass.

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex2-dogYears.js
> +  return `Your doggie is ${realAge} years old in dog years!`;
🎉

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +  const numKids = [1, 2, 3, 4];
If you read the exercise again, you need to put 5 values for `numKids` and also `partnerNames` for the test to pass. Otherwise great job on the function.

You also need to use western names for the partnerNames (I know the test is not diverse as we are 🥲)

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex4-shoppingCart.js
> +  shoppingCart.push(item);
this is great work, and the tests all pass. 

However, I think we should add one more test. What will happen if your shoppingCart is like this `['bananas', 'milk', '']`

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex5-shoppingCartPure.js
> +  return newShoppingCart;
great attempt here, however, the functions `shift` and `splice` are both mutating functions. I'd advise you to give this another go using non-mutating functions (functions that return a new array) as the requirement here is to do it in a pure way.

Keep line 20. That is part of the correct approach. 

I also don't understand why you had to loop over the array to splice, can you explain to me how you approached this question?

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
> +  const amount = Object.values(myObject).reduce((a, b) => a + b, 0);
Great work on this question. Even more impressive that you used reduce.

2023-01-14 02:59 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex7-mindPrivacy.js
> +  return newArr;
This is correct, however, I was hoping to see you used `.map` here because I was already impressed you used `.reduce()` in the above exercise 6 (no pressure 😅). 
If you want to change it, it's up to you.

2023-01-14 03:14 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +  const numKids = [1, 2, 3, 4];
The five values are (1 kid, 2 kids, 3 kids, 4 kids, and 5 kids), and there is also five names for `partnerNames` , I can't see the problem you're pointing at.

The names of the partners are all western, non of which are eastern.

2023-01-14 03:23 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +  const numKids = [1, 2, 3, 4];
`Give each array five random values that have to do with the name of 
   the variable.`
There are 4 names, and only 4 number values in the numKids array. 

Job title and locations seem okay. 

You can also see the test file that failed and you will see where the error is.

2023-01-14 03:47 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex4-shoppingCart.js
> +  shoppingCart.push(item);
Doesn't this assumption make the array length already = 3 even before adding to it? that means we can't add to it or the 1st item will be removed

2023-01-14 04:08 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex5-shoppingCartPure.js
> +  return newShoppingCart;
I even didn't get the rule very well.
The rule says that if the `newShoppingCart` > 3, then the first item should be removed. But this contradicts the request to keep the passed `shoppingCart` array unmutated since the first item in the `newShoppingCart` is the first item in the passed `shoppingCart`

2023-01-14 04:11 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex7-mindPrivacy.js
> +  return newArr;
Will, this is even not my solution 😅, my mind then was so stuck and I asked for help and copy-paste. But I'll review it to add my solution

2023-01-14 04:37 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex1-giveCompliment.js
> +  return `You are ${compliments[randomCompliment]}, ${name}`;
Done

2023-01-14 17:07 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex5-shoppingCartPure.js
> +  return newShoppingCart;
Jalal, I read this function again, and I think its ok for me in terms of pure implementation. Because even though you used mutating functions, you used them on the array copy `newShoppingCart`. I think you can just improve the function and refactor it a bit. I don't think you need that loop at all.

In regards to your question, this is how it works:

Let's assume you get the shopping cart like this
`const oldShoppingCart = ['apple', 'rice', 'choco', 'kiwi', 'lemon']`
You also get a new groceryItem 'coffee'.

The requirement is first make a copy of the oldShoppingCart (because we don't want to change it)
`const newShoppingCart = [...oldShoppingCart]`

Then secondly, add the groceryItem.
`newShoppingCart.push(groceryItem)`

Now, if you console log the newShoppingCart (you will have 6 items). But you should return only the last three items in the cart.

So, if you look which array functions you have which return a new array, you can do this

```
const onlyLast3Items = newShoppingCart.slice(3);
return onlyLast3Items;

2023-01-14 17:09 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex4-shoppingCart.js
> +  shoppingCart.push(item);
yeah, you can do it, but it will be like this ['milk', '', 'newItem'] and when you join them by comma you get this `You bought milk, , newItem` (notice the extra comma in between

2023-01-14 17:14 UTC, abbathaw commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
> +calculateTotalPrice(cartForParty);
btw, there are two tests below which you need to also add :) I didn't notice them earlier.

2023-01-14 19:16 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex4-shoppingCart.js
> +  shoppingCart.push(item);
Of course. 
BUT, regardless of the rules of this exercise, we can push the new item to the specific empty string and get rid of this empty string, right?

2023-01-14 19:23 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex5-shoppingCartPure.js
> +  return newShoppingCart;
Ok thanks. 
I did some modifications and pushed the changes to GitHub but not sure if the pull request also receive these changes.

2023-01-14 19:25 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
> +calculateTotalPrice(cartForParty);
They are 2 test indeed and all passed correctly.

2023-01-29 10:59 UTC, JalalHabeeb commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
> +calculateTotalPrice(cartForParty);
Oh yeah, I've just noticed. I have to write tests. Sorry for that, I was out of my mind.  I'll do them today.

2023-02-01 12:05 UTC, abbathaw approved these changes

2023-07-15 12:40 UTC, closed without merging