Jalalhabeeb browser week1
HackYourHomework/Homework-class42 pull request #38
Opened 2023-01-24 22:52 UTC by JalalHabeeb

2023-01-27 23:09 UTC, kasimoglou requested changes
Well done Jalal! The first 4 exercises work perfectly, the 5th needs some more work but you are in the right direction!

Test results are not included in the PR, I run them locally and I saw that they fail for the second exercise as the `body` element does not have the required font family. Could you please include this fix?

Also, this MR contains exercises from previous weeks. It would be very helpful if the next time you could create a brand new branch from the main branch and include there only the changes that are relevant to the corresponding week. Please let me know if you need help on how exactly you could do that.

2023-01-28 16:02 UTC, JalalHabeeb commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +homeTown.textContent = 'Homs';
Yes indeed, I should've followed DRY concept.

2023-01-28 16:06 UTC, JalalHabeeb commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    container.textContent = `Local Time is: ${time.getHours()}:${time.getMinutes()}:${time.getSeconds()}`;
I will of course, but anyway this Date object still confuses me everytime I deal with it.

2023-01-28 16:09 UTC, JalalHabeeb commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      currentLeft = image.style.left + 10 + 'px';
This whole solution is a mess I know. I was working on it and it was moving but not repeating when reach the edge, so I deleted everything and started over.
I'll work on it.

2023-01-28 16:13 UTC, JalalHabeeb commented
About the body font family, this is a test that remained from another test method, it's an error in the test itself, I told Rob about it and I think he fixed it.
About the exercises from another week, they are here because in week 1 I didn't make a branch and worked directly in the main branch, and now I don't know how to fix this. can you help me with it?

2023-02-26 21:34 UTC, kasimoglou approved these changes

2023-07-15 12:40 UTC, closed without merging